
# Use environment variables for API keys
GOOGLE_MAPS_API_KEY = "AIzaSyDN0wDU4FYOjdAiHOc4WiH4cZR58TNPFNo"

TIER_API_KEY = "bpEUTJEBTf74oGRWxaIcW7aeZMzDDODe1yBoSxi2"

BIRD_API_KEY = "bpEUTJEBTf74oGRWxaIcW7aeZMzDDODe1yBoSxi2"
